#!/usr/bin/env ruby

require File.expand_path('../config/environment', __dir__)

require 'telegram/bot'

token = Rails.application.credentials.telegram[:token]

Telegram::Bot::Client.run(token) do |bot|
  bot.listen do |message|
    greetings = %w[Hola Bonjour Namaste Hello].sample
    greet = "#{greetings} #{message.from.first_name}, Welcome to Personal Remote Job Board"
    tech_question = 'Please tel me in which technology you are looking for job'
    answers = Telegram::Bot::Types::ReplyKeyboardMarkup
      .new(keyboard: %w[Rails Python], one_time_keyboard: true)

    case message.text
    when '/start'
      bot.api.send_message(chat_id: message.chat.id, text: greet)
      bot.api.send_message(chat_id: message.chat.id, text: tech_question, reply_markup: answers)
    when 'Rails'
      bot.api.send_message(chat_id: message.chat.id, text: "Here it is the list #{message.from.first_name}")
      Job.where(technology: 'rails').map { |item| bot.api.send_message(chat_id: message.chat.id, text: item.link) }
    when 'Python'
      bot.api.send_message(chat_id: message.chat.id, text: "Here it is the list #{message.from.first_name}")
      Job.where(technology: 'python').map { |item| bot.api.send_message(chat_id: message.chat.id, text: item.link) }
    else
      bot.api.send_message(chat_id: message.chat.id, text: "Sorry #{message.from.first_name}, Currently we didnt have the jobs, will add soon.") 
    end
  end
end
