#!/usr/bin/env ruby

require File.expand_path('../config/environment', __dir__)

require 'telegram/bot'

token = Rails.application.credentials.telegram[:token]

Telegram::Bot::Client.run(token) do |bot|
  bot.listen do |message|
    greetings = %w[Hola Bonjour Namaste Hello].sample
    greet = "#{greetings} #{message.from.first_name}, Welcome to Personal Remote Job Board"
    tech_question = 'Please tel me in which technology you are looking for job'
    answers = Telegram::Bot::Types::ReplyKeyboardMarkup
      .new(keyboard: %w[/Rails /React /Python /Other], one_time_keyboard: true)

    case message.text
    when '/start'
      bot.api.send_message(chat_id: message.chat.id, text: greet)
      bot.api.send_message(chat_id: message.chat.id, text: tech_question, reply_markup: answers)
    else
      bot.api.send_message(chat_id: message.chat.id, text: "Here it is the list #{message.from.first_name}")
      # Job.all.each { |item| bot.api.send_message(chat_id: message.chat.id, text: item.to_s) }
    end
  end
end
